= XML:DB Initiative for XML Databases
Patrick Reinhart <https://github.com/reinhapa[@reinhapa]>
:project-full-path: xmldb-org/xmldb-api
:github-branch: master

image:https://img.shields.io/badge/license-XML:DB-blue.svg["XML:DB Initiative Software License", link="https://github.com/{project-full-path}/blob/{github-branch}/LICENSE"]
image:https://img.shields.io/badge/Java-8-blue.svg["Java 8", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/badge/Java-11-blue.svg["Java 11", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/badge/Java-15-blue.svg["Java 15", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/github/release/{project-full-path}.svg["Release", link="https://github.com/{project-full-path}/releases"]
image:https://github.com/{project-full-path}/workflows/CI/badge.svg["Java CI with Gradle", link="https://github.com/{project-full-path}/actions?query=workflow%3ACI"]

This is a conversion to Git of the `xapi` module from the XML:DB CVS repositiory
via `anonymous@a.cvs.sourceforge.net:/cvsroot/xmldb-org`.

The archived project and code can be found at https://sourceforge.net/projects/xmldb-org/


== Content
The API interfaces are what driver developers must implement when creating a
new driver and are the interfaces that applications are developed against.
Along with the interfaces a concrete DriverManager implementation is also
provides.


== Building for eXist-db
The XML:DB API can be built as a JAR file. This is also used by http://exist-db.org/[eXist-db]'s 
implementation of the XML:DB API.

Java 8 or later is required to build the JAR file.

[source,bash]
----
$ git clone https://github.com/xmldb-org/xmldb-api.git
$ cd xmldb-api
$ gradlew build
----

The JAR file will be located in the `build/libs` folder.


== Getting the binaries for your build:
The latest versions of the API are available at https://search.maven.org/search?q=g:net.sf.xmldb-org


== Contribute
Contributions are always welcome. Use https://google.github.io/styleguide/javaguide.html[Google code style format] for your changes. 


== License
This project is licensed under the https://github.com/{project-full-path}/blob/{github-branch}/LICENSE[XML:DB Software license]