= XML:DB Initiative for XML Databases
Patrick Reinhart <https://github.com/reinhapa[@reinhapa]>
:group-name: net.sf.xmldb-org
:project-org: xmldb-org
:project-name: xmldb-api
:project-full-path: {project-org}/{project-name}
:github-branch: master

image:https://img.shields.io/badge/license-XML:DB-blue.svg["XML:DB Initiative Software License", link="https://github.com/{project-full-path}/blob/{github-branch}/LICENSE"]
image:https://img.shields.io/github/release/{project-full-path}.svg["Release", link="https://github.com/{project-full-path}/releases"]
image:https://img.shields.io/maven-central/v/{group-name}/{project-name}.svg?label=Maven%20Central["Maven Central", link="https://search.maven.org/search?q=g:%22{group-name}%22%20AND%20a:%22{project-name}%22"]
image:https://sonarcloud.io/api/project_badges/measure?project={project-org}_{project-name}&metric=alert_status["Quality Gate Status", link ="https://sonarcloud.io/summary/new_code?id={project-org}_{project-name}"]
image:https://javadoc.io/badge2/{group-name}/{project-name}/javadoc.svg["javadoc", link="https://javadoc.io/doc/{group-name}/{project-name}"]
image:https://github.com/{project-full-path}/actions/workflows/gradle.yml/badge.svg["CI", link="https://github.com/{project-full-path}/actions/workflows/gradle.yml"]


This is a conversion to Git of the `xapi` module from the XML:DB CVS repository
via `anonymous@a.cvs.sourceforge.net:/cvsroot/xmldb-org`.

The archived project and code can be found at https://sourceforge.net/projects/xmldb-org/

Supported Java versions: 
image:https://img.shields.io/badge/Java-17-blue.svg["Java 17", link="https://adoptium.net/"]
image:https://img.shields.io/badge/Java-21-blue.svg["Java 21", link="https://adoptium.net/"]

== Content
The API interfaces are what driver developers must implement when creating a
new driver and are the interfaces that applications are developed against.
Along with the interfaces a concrete DriverManager implementation is also
provides.

== Building for eXist-db
The XML:DB API can be built as a JAR file. This is also used by http://exist-db.org/[eXist-db]'s 
implementation of the XML:DB API.

Java 11 or later is required to build the JAR file.

[source,bash,subs="attributes"]
----
$ git clone https://github.com/{project-full-path}.git
$ cd {project-name}
$ gradlew build
----

The JAR file will be located in the `build/libs` folder.


== Getting the binaries for your build:
The latest versions of the API are available at https://search.maven.org/search?q=g:{group-name}

Snapshot builds are available from the Maven snapshot repository
https://oss.sonatype.org/content/repositories/snapshots/net/sf/xmldb-org/xmldb-api/[https://oss.sonatype.org/content/repositories/snapshots]


== Contribute
Contributions are always welcome. Use https://google.github.io/styleguide/javaguide.html[Google code style format] for your changes. 


== License
This project is licensed under the https://github.com/{project-full-path}/blob/{github-branch}/LICENSE[XML:DB Software license]